config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'get_tx_details/:id' => 'welcome#get_tx_details'
  get 'get_lineage/:id' => 'welcome#get_lineage'
  get 'get_utx' => 'welcome#get_utx'

end

app/models/transaction.rb
class Transaction
  include Mongoid::Document
  store_in collection: 'Transaction', database: 'bitcoin'
  
  field :out, type: Array
  field :relayed_by, type: String
  field :inputs, type: Array
  field :ver, type: Integer
  field :lock_time, type: Integer
  field :size, type: Integer
  field :time, type: Integer
  field :tx_index, type: Integer
  field :vin_sz, type: Integer
  field :vout_sz, type: Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  
  def index
    @tx_id = params[:tx_id]
  end
  
  def get_tx_details
    @tx = Transaction.find(params[:id])
    render json: @tx
  end
  
  def get_utx
    @utx = Transaction.where({"blockHash" => {"$exists" => 0}}).limit(100)  
  end
  
  def get_lineage
    client = Mongoid.client('default')
    tx_id = params[:id]
    
    agg = {
  "aggregate"=> "Transaction",
  "allowDiskUse" => true,
  "pipeline"=> [
    { "$match"=> { "_id"=> tx_id } },
    { "$project"=> {
      "input_addr"=>"$inputs.prev_out.addr"
    }
    },
  { "$unwind"=> "$input_addr" },
  { "$graphLookup"=>
    {
      "from"=> "Transaction",
      "startWith"=> "$input_addr",
      "connectFromField"=> "inputs.prev_out.addr",
      "connectToField"=> "out.addr",
      "as"=> "source",
      "maxDepth"=> 4,
      "depthField"=> "depth"
    }
    },
  { "$unwind"=> "$source" },
  { "$project"=>
    {
      "_id"=> 0,
      "toAddr"=>  "$source.out.addr",
      "fromtx"=> "$source._id",
      "address"=> "$source.inputs.prev_out.addr",
      "satoshi"=> "$source.inputs.prev_out.value",
      "depth"=> "$source.depth",
	  "time"=> "$time"
    }
    },
  { "$unwind"=> "$satoshi" },
  { "$unwind"=> "$address" },
  {
      "$group"=> {
        "_id" => "$depth",
        transactions: {
          "$push" => {
            "toAddr"=> "$toAddr",
            "fromtx"=> "$fromtx",
            "address"=> "$address",
            "satoshi"=> "$satoshi",
          }
        }
      }
    },
  { "$sort"=> { "_id"=> 1 } }
  ]
}
    
    result = client.command(agg)
  
    @lineage = result.documents[0]['result']

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlockchainDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/get_lineage.html.erb
<% @lineage.each do |doc| %>

  <%= doc['transactions'] %>
  <p/>

<% end %>

<!-- <%= @lineage %> -->

app/views/welcome/get_tx_details.html.erb
<%= @tx %>

app/views/welcome/get_utx.html.erb
<html>
<head>
  <style>
    body {
      font-family: helvetica;
    }
    td, th {
      padding: 5px;
    }
    th {
      background-color: tan;
    }
    .centertext {
      text-align: center;
    }
    .lightgrey {
      background-color: #E6E6E6
    }
    .fixedwidth {
      font-family: courier;
    }
    .rightalign {
      text-align: right;
    }
    .small {
      font-size: small;
    }
	
    a:link, a:visited {
		color: darkblue;
    	text-decoration: none;
    }
  </style>
  <title>Uncommitted Transactions</title>
</head>
<body>
<table border='1'>
  <tr>
    <td colspan='5' class='centertext'><h2>Uncommitted Transactions</h2></td>
  </tr>
  
  <tr>
    <th>Record ID</th>
    <th>From Account</th>
    <th># of Inputs</th>
    <th>Total Coin (in Satoshis)</th>
    <th>To Account</th>
  </tr>
  
  <% @utx.each_with_index do |doc, i| %>
    <% i % 2 == 0 ? bg_color = 'lightgrey' : bg_color = 'none' %>
    <% inputs_length = doc[:inputs].length %>
    <% from = doc[:inputs][0]['prev_out']['addr'] %>
    <% to = doc[:out][0]['addr'] %>
    <% total = doc[:inputs][0]['prev_out']['value'] %>
    <% tid = doc[:_id] %>
    <tr class=<%= bg_color %>>
	            <td class='small'><%= link_to(tid, root_path(tx_id: tid))  %></td>
                <td class='fixedwidth'><%= from %></td>
                <td class='centertext'><%= inputs_length %></td>
                <td class='rightalign'><%= total %></td>
                <td class='fixedwidth'><%= to %></td>
              </tr>
  <% end %>
  
  </table></body></html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
 
<%= javascript_include_tag "jquery.min.js" %>
<%= javascript_include_tag "jquery-ui.min.js" %>  
<%= javascript_include_tag "d3.js" %>
<%= javascript_include_tag "dndTree.js" %>

<body>
	
	<div class='txname' data-txname=<%= @tx_id %>></div>
	
	<div class='topnav' style="font-family: helvetica; margin: 20px;">
		<%= link_to "Uncommitted Transactions", get_utx_path %>
	</div>
	
	<script>

    
    $(function() {
      $( document ).tooltip();
    });
	
	</script>
    
	<div id="tree-container"></div>
</body>
</html>
  